### ISSUE TITLE
how to convert decimal digit

### ISSUE THREAD

**Issue by Noman73** [forzagreen/n2words#35] opened 2020-10-29 12:40 UTC
how can i convert decimal digit?? 
like
` 1.5 ="one point five"`

**Comment by forzagreen** [comment] 2020-10-29 13:18
We have just merged a first version of decimal number in https://github.com/forzagreen/n2words/pull/34 
It will be ready in the next release

**Closed** 2020-10-29 13:19 UTC

**Comment by forzagreen** [comment] 2020-10-29 13:20
Duplicate of https://github.com/forzagreen/n2words/issues/33
