### ISSUE TITLE
Incorrect 99 translate in polish

### ISSUE THREAD

**Issue by FSkwierawski** [forzagreen/n2words#52] opened 2021-07-12 10:23 UTC
Actually 90 is translated to "dziewięćdzisiąt" where correctly is "dziewięćdzi**e**siąt". There is "e" letter missing. Also number like 91, 92 etc, need fix.

**Comment by forzagreen** [comment] 2021-08-14 11:26
Thank you @FSkwierawski  for reporting.
Duplicate of https://github.com/forzagreen/n2words/issues/48. Fixed in https://github.com/forzagreen/n2words/pull/49. Released in [v1.9.1](https://github.com/forzagreen/n2words/releases/tag/v1.9.1)

**Closed by forzagreen** 2021-08-14 11:26 UTC
Labels: bug, duplicate
